project_id = "qyqeibovdhyohkfagujv"

[functions.fetch-dvsa-news]
verify_jwt = false

[functions.send-gap-sms]
verify_jwt = false

[functions.send-lesson-reminders]
verify_jwt = false

[functions.notify-instructor]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false
