import {
  CalendarDays, Users, MapPin, PoundSterling, Navigation,
  Car, Lightbulb, Crown, CalendarPlus, ListTodo,
  Wrench, Fuel, ClipboardCheck, ArrowLeftRight, Target,
  MessageSquare, MapPinned, BookOpen, Settings,
  Gift, Clock, Receipt, FileBarChart, BarChart3, Moon, Megaphone,
  FolderLock, Timer, Hash, Heart, CalendarClock,
  Sparkles, GitBranch, FileCheck, ShoppingCart, ClipboardList,
  UserCheck, Award, TrendingUp,
  type LucideIcon,
} from "lucide-react";

export interface DiscoverFeature {
  title: string;
  icon: LucideIcon;
  accent: string;
  route: string;
  summary: string;
  detailedDescription: string;
  category: string;
}

export const FEATURE_CATEGORIES = [
  "Scheduling",
  "Money & Payments",
  "Lesson Tracking",
  "Tools & Navigation",
  "Reports & Insights",
  "Growth & Community",
  "Settings & Admin",
] as const;

export const DISCOVER_FEATURES: DiscoverFeature[] = [
  // Scheduling
  {
    title: "Agenda",
    icon: CalendarDays,
    accent: "#007AFF",
    route: "/instructor/schedule",
    summary: "View and manage your daily and weekly lesson schedule.",
    detailedDescription: "Your full calendar showing all booked lessons, personal events, and available slots. Tap any slot to add a lesson or block time. Swipe between day, week, and month views. Conflicts are highlighted automatically so you never double-book.",
    category: "Scheduling",
  },
  {
    title: "Fill Gaps",
    icon: CalendarPlus,
    accent: "#FF2D55",
    route: "/instructor/gaps",
    summary: "Broadcast open slots to pupils waiting for lessons.",
    detailedDescription: "When a cancellation happens or you have spare capacity, create a gap slot with one tap. Eligible pupils are automatically notified and can claim the slot instantly. Reduces empty hours and boosts your weekly earnings.",
    category: "Scheduling",
  },
  {
    title: "Availability",
    icon: Clock,
    accent: "#34C759",
    route: "/instructor/availability",
    summary: "Set your regular working hours and days off.",
    detailedDescription: "Define your weekly working pattern, add holidays, and set recurring days off. Your availability feeds into the booking system so pupils can only request times you're actually free. Changes notify affected pupils automatically.",
    category: "Scheduling",
  },
  {
    title: "Plan Ahead",
    icon: Lightbulb,
    accent: "#FFCC00",
    route: "/instructor/diary",
    summary: "Preview tomorrow's lessons and plan your route.",
    detailedDescription: "See what's coming up tomorrow at a glance — pickup addresses, lesson types, and any notes. Plan your driving route between pupils to minimise dead miles and arrive on time every time.",
    category: "Scheduling",
  },

  // Money & Payments
  {
    title: "Take Payment",
    icon: PoundSterling,
    accent: "#AF52DE",
    route: "/instructor/pay",
    summary: "Record cash, card, or bank transfer payments.",
    detailedDescription: "Log payments from pupils quickly with amount, method, and optional notes. See who owes money at a glance and send payment reminders with one tap. Supports cash, bank transfer, and card payments.",
    category: "Money & Payments",
  },
  {
    title: "Expenses",
    icon: Receipt,
    accent: "#FF9500",
    route: "/instructor/expenses",
    summary: "Track fuel, car maintenance, and business costs.",
    detailedDescription: "Log business expenses with receipt photos, categories, and amounts. See your monthly spending breakdown and export data for your tax return. Categories include fuel, insurance, car maintenance, and more.",
    category: "Money & Payments",
  },
  {
    title: "Month End",
    icon: FileBarChart,
    accent: "#5856D6",
    route: "/instructor/month-end",
    summary: "Review monthly earnings, expenses, and profit.",
    detailedDescription: "A complete end-of-month financial summary showing total lessons, earnings, expenses, and net profit. Export reports for your accountant or HMRC. Compare month-on-month performance to spot trends.",
    category: "Money & Payments",
  },

  // Lesson Tracking
  {
    title: "Track Lesson",
    icon: MapPin,
    accent: "#E15D5A",
    route: "/instructor/tracking",
    summary: "GPS-track lessons in real time with route recording.",
    detailedDescription: "Start GPS tracking when a lesson begins to record the exact route driven. See speed, distance, and duration in real time. The route is saved to the pupil's history so you can review areas covered and plan future lessons.",
    category: "Lesson Tracking",
  },
  {
    title: "Log Test Result",
    icon: ClipboardCheck,
    accent: "#007AFF",
    route: "/instructor/test-results",
    summary: "Record driving test results and fault analysis.",
    detailedDescription: "Log pass/fail results with the full DVSA fault breakdown — minor, serious, and dangerous faults by category. Track your pass rate over time and identify common fault areas across all your pupils to improve your teaching.",
    category: "Lesson Tracking",
  },
  {
    title: "Standards Check",
    icon: Target,
    accent: "#E15D5A",
    route: "/instructor/standards-check",
    summary: "Prepare for your DVSA Standards Check assessment.",
    detailedDescription: "Review the 17 competency areas assessed during a Standards Check. Log practice sessions, track your readiness score, and access tips for each competency. Set reminders so you're never caught off guard.",
    category: "Lesson Tracking",
  },

  // Tools & Navigation
  {
    title: "SatNav",
    icon: Navigation,
    accent: "#007AFF",
    route: "/instructor/satnav",
    summary: "Built-in navigation for lesson routes.",
    detailedDescription: "Full turn-by-turn navigation designed for driving instructors. Set test routes, save favourite routes, and navigate to pupil pickup addresses. Works offline once routes are cached.",
    category: "Tools & Navigation",
  },
  {
    title: "Find My Car",
    icon: Car,
    accent: "#FF9500",
    route: "/instructor/find-my-car",
    summary: "See your car's last known GPS position.",
    detailedDescription: "Quickly locate your parked car using the last recorded GPS position. Useful when you park at a test centre or between lessons. Shows distance and walking directions to your vehicle.",
    category: "Tools & Navigation",
  },
  {
    title: "Find Fuel",
    icon: Fuel,
    accent: "#34C759",
    route: "/instructor/fuel",
    summary: "Find the cheapest nearby petrol stations.",
    detailedDescription: "See fuel prices at stations near you, sorted by price or distance. Filter by fuel type (petrol, diesel) and see real-time prices. Save your favourite stations for quick reference.",
    category: "Tools & Navigation",
  },
  {
    title: "Find Nearby",
    icon: MapPin,
    accent: "#0EA5E9",
    route: "/instructor/find-nearby",
    summary: "Locate toilets, cafés, and rest stops nearby.",
    detailedDescription: "Search for nearby amenities between lessons — public toilets, cafés, parking, and rest areas. Filtered results show distance and opening hours so you can plan your breaks efficiently.",
    category: "Tools & Navigation",
  },
  {
    title: "Locations",
    icon: MapPinned,
    accent: "#E15D5A",
    route: "/instructor/locations",
    summary: "Save frequently visited addresses and meeting points.",
    detailedDescription: "Pin your most-used locations — test centres, pupil homes, practice areas. Quickly navigate to saved locations or share them with pupils. Organise with custom labels and categories.",
    category: "Tools & Navigation",
  },
  {
    title: "Vehicle Health",
    icon: Wrench,
    accent: "#8E8E93",
    route: "/instructor/vehicle-health",
    summary: "Track MOT, service dates, and vehicle documents.",
    detailedDescription: "Keep all vehicle compliance in one place — MOT expiry, service schedules, insurance renewal, and breakdown cover. Get automatic reminders before anything expires so you're always road-legal.",
    category: "Tools & Navigation",
  },

  // Reports & Insights
  {
    title: "Weekly Report",
    icon: BarChart3,
    accent: "#7C3AED",
    route: "/instructor/weekly-report",
    summary: "AI-generated summary of your week's performance.",
    detailedDescription: "An intelligent weekly digest covering lessons taught, earnings, pupil progress, and areas for improvement. Compare with previous weeks and get actionable suggestions to optimise your schedule and income.",
    category: "Reports & Insights",
  },
  {
    title: "End of Day",
    icon: Moon,
    accent: "#6366F1",
    route: "/instructor/end-of-day",
    summary: "Quick daily summary of lessons and earnings.",
    detailedDescription: "At the end of each teaching day, see a snapshot of lessons completed, money earned, and any follow-ups needed. Share the summary or save it for your records. A great way to wind down and stay on top of admin.",
    category: "Reports & Insights",
  },
  {
    title: "Tasks Due",
    icon: ClipboardCheck,
    accent: "#EA580C",
    route: "/instructor/outstanding-tasks",
    summary: "View outstanding follow-ups and admin tasks.",
    detailedDescription: "A central list of everything that needs your attention — unpaid invoices, unsigned documents, lesson notes to complete, and pupil follow-ups. Clear tasks as you go to keep your admin at zero.",
    category: "Reports & Insights",
  },

  // Growth & Community
  {
    title: "Pupils",
    icon: Users,
    accent: "#34C759",
    route: "/instructor/pupils",
    summary: "Manage your full pupil list and their progress.",
    detailedDescription: "Your complete pupil database with contact details, lesson history, progress tracking, and payment records. Add new pupils, update their details, and view their syllabus completion at a glance.",
    category: "Growth & Community",
  },
  {
    title: "Messages",
    icon: MessageSquare,
    accent: "#007AFF",
    route: "/instructor/messages",
    summary: "In-app messaging with your pupils.",
    detailedDescription: "Send and receive messages with pupils directly in the app. Use quick templates for common messages like lesson confirmations and reminders. See read receipts and keep all communication in one place.",
    category: "Growth & Community",
  },
  {
    title: "Referrals",
    icon: Gift,
    accent: "#FF2D55",
    route: "/instructor/referrals",
    summary: "Earn rewards by referring new instructors.",
    detailedDescription: "Share your referral code with fellow driving instructors. When they sign up and become active, you both earn rewards. Track your referral stats and see your earned bonuses.",
    category: "Growth & Community",
  },
  {
    title: "Test Swap",
    icon: ArrowLeftRight,
    accent: "#FF9500",
    route: "/instructor/test-requests",
    summary: "Exchange test dates with other instructors.",
    detailedDescription: "If a pupil's test date doesn't suit, post it for swap with other instructors in your area. Browse available swaps and negotiate directly. A great way to get your pupil a better date.",
    category: "Growth & Community",
  },
  {
    title: "Nearby ADIs",
    icon: Users,
    accent: "#5856D6",
    route: "/instructor/nearby-friends",
    summary: "See other instructors in your area on a live map.",
    detailedDescription: "Connect with nearby driving instructors for support, test swaps, and community. See who's active in your area and reach out directly. Build your local instructor network.",
    category: "Growth & Community",
  },
  {
    title: "Waiting Room",
    icon: Users,
    accent: "#2563EB",
    route: "/instructor/waiting-room",
    summary: "Weekly Zoom catch-up for driving instructors.",
    detailedDescription: "An informal weekly video call where instructors share tips, discuss challenges, and support each other. Open to all ADIs — no agenda, just conversation. A great way to stay connected with the community.",
    category: "Growth & Community",
  },
  {
    title: "Platform Updates",
    icon: Megaphone,
    accent: "#6366F1",
    route: "/instructor/platform-updates",
    summary: "Latest news, features, and app updates.",
    detailedDescription: "Stay up to date with new features, bug fixes, and improvements. Read about upcoming releases and share your feedback. We build what instructors actually need.",
    category: "Growth & Community",
  },

  // Settings & Admin
  {
    title: "To Do",
    icon: ListTodo,
    accent: "#5AC8FA",
    route: "/instructor/todos",
    summary: "Personal task list for admin and follow-ups.",
    detailedDescription: "A simple, quick-access to-do list for things you need to remember — call a pupil back, chase a payment, book car service. Add tasks in seconds and tick them off as you go.",
    category: "Settings & Admin",
  },
  {
    title: "CPD Log",
    icon: BookOpen,
    accent: "#5856D6",
    route: "/instructor/cpd",
    summary: "Log continuing professional development hours.",
    detailedDescription: "Record your CPD activities including courses, workshops, online training, and peer observations. Track your annual hours and export a certificate-ready log for your records or DVSA requirements.",
    category: "Settings & Admin",
  },
  {
    title: "Your Plan",
    icon: Crown,
    accent: "#AF52DE",
    route: "/instructor/plans",
    summary: "View and manage your subscription plan.",
    detailedDescription: "See your current plan details, billing history, and available upgrades. Compare plan features and switch tiers at any time. Your subscription unlocks premium features like GPS tracking and AI reports.",
    category: "Settings & Admin",
  },
  {
    title: "Settings",
    icon: Settings,
    accent: "#8E8E93",
    route: "/instructor/settings",
    summary: "Customise your app preferences and profile.",
    detailedDescription: "Update your profile, notification preferences, lesson defaults, and display settings. Configure your hourly rate, working hours, and communication preferences. Everything in one place.",
    category: "Settings & Admin",
  },
  // Operations & Team
  {
    title: "Digital Checklists",
    icon: ClipboardCheck,
    accent: "#34C759",
    route: "/instructor/checklists",
    summary: "Pre-lesson vehicle checks, incident reports, and end-of-day sign-offs.",
    detailedDescription: "Create reusable checklist templates for pre-lesson vehicle inspections, incident reports, and end-of-day sign-offs. Complete them with photo evidence and digital signatures. Full submission history for compliance.",
    category: "Tools & Navigation",
  },
  {
    title: "Document Vault",
    icon: FolderLock,
    accent: "#5856D6",
    route: "/instructor/document-vault",
    summary: "Secure storage for contracts, insurance, and training certificates.",
    detailedDescription: "Upload and organise your important documents in one secure location. Categorise by type — contracts, insurance, licences, training certificates. Search and filter to find what you need instantly.",
    category: "Settings & Admin",
  },
  {
    title: "Clock In/Out",
    icon: Timer,
    accent: "#FF9500",
    route: "/instructor/clock",
    summary: "GPS-verified time tracking for your working day.",
    detailedDescription: "Clock in and out with GPS verification to accurately track your working hours. View weekly totals, daily breakdowns, and location stamps for each entry. Perfect for franchise instructors who need to log hours.",
    category: "Tools & Navigation",
  },
  {
    title: "Team Channels",
    icon: Hash,
    accent: "#007AFF",
    route: "/instructor/team-channels",
    summary: "Topic-based group messaging for your team.",
    detailedDescription: "Create channels for different topics — general chat, pass celebrations, shift cover requests. Real-time messaging with your team of instructors. Keep conversations organised and searchable.",
    category: "Growth & Community",
  },
  {
    title: "Wellbeing",
    icon: Heart,
    accent: "#FF2D55",
    route: "/instructor/wellbeing",
    summary: "Daily mood and energy tracking to prevent burnout.",
    detailedDescription: "Log your daily mood, energy, and stress levels with a quick tap. Track trends over 14 days to spot early signs of burnout. Add notes to reflect on what's affecting your wellbeing.",
    category: "Tools & Navigation",
  },
  {
    title: "Availability Windows",
    icon: CalendarClock,
    accent: "#34C759",
    route: "/instructor/availability-windows",
    summary: "Set your recurring weekly working hours.",
    detailedDescription: "Define your standard weekly availability with recurring time windows for each day. Toggle slots on and off as needed. Simplifies scheduling by showing pupils when you're available to teach.",
    category: "Scheduling",
  },
  {
    title: "AI Command Centre",
    icon: Sparkles,
    accent: "#AF52DE",
    route: "/instructor/ai-command",
    summary: "Natural language commands to manage your business.",
    detailedDescription: "Type or speak commands like 'Book Sarah for Thursday 2pm' or 'Show this week's earnings'. The AI understands your pupils, schedule, and finances and executes actions instantly.",
    category: "Tools & Navigation",
  },
  {
    title: "Workflow Builder",
    icon: GitBranch,
    accent: "#5856D6",
    route: "/instructor/workflows",
    summary: "Multi-step automations with conditions and delays.",
    detailedDescription: "Build advanced if-this-then-that workflows with conditions (e.g. pupil balance > £50), time delays, and chained actions like SMS, notes, and pipeline moves. Goes beyond simple automations.",
    category: "Settings & Admin",
  },
  {
    title: "Digital Waivers",
    icon: FileCheck,
    accent: "#5856D6",
    route: "/instructor/waivers",
    summary: "Create and manage consent forms and waivers.",
    detailedDescription: "Create waiver templates (medical declarations, terms & conditions, parental consent). Track which pupils have signed. Send reminders to those who haven't. All signatures are timestamped with IP address.",
    category: "Settings & Admin",
  },
  {
    title: "Abandoned Checkouts",
    icon: ShoppingCart,
    accent: "#FF9500",
    route: "/instructor/abandoned-checkouts",
    summary: "Recover bookings that didn't complete payment.",
    detailedDescription: "Track prospective pupils who started booking but didn't finish payment. Send automated follow-up reminders via SMS or email. Monitor conversion rates from remarketing efforts.",
    category: "Growth & Community",
  },
  {
    title: "Daily Manifest",
    icon: ClipboardList,
    accent: "#007AFF",
    route: "/instructor/daily-manifest",
    summary: "Printable day sheet with all lesson details.",
    detailedDescription: "View your full day at a glance: pupil names, pickup addresses, phone numbers, lesson types, and payment status. Print or download as PDF. Check in pupils as lessons start.",
    category: "Scheduling",
  },
  {
    title: "Waiting List",
    icon: UserCheck,
    accent: "#34C759",
    route: "/instructor/waiting-list",
    summary: "Manage queue priority when your schedule is full.",
    detailedDescription: "When your schedule is full, pupils can join a waiting list. When a cancellation occurs, the system offers the slot to waiting pupils in order, with timed claim windows before escalating to the next person.",
    category: "Scheduling",
  },
  {
    title: "Certifications",
    icon: Award,
    accent: "#AF52DE",
    route: "/instructor/certifications",
    summary: "Track pupil milestones and award certificates.",
    detailedDescription: "Award milestones like Theory Ready, Practical Ready, Course Complete, and Test Passed. View a visual progress timeline for each pupil showing their journey from first lesson to test pass.",
    category: "Lesson Tracking",
  },
  {
    title: "EOD Report",
    icon: TrendingUp,
    accent: "#FF2D55",
    route: "/instructor/eod-report",
    summary: "Enhanced end-of-day report with payment breakdown.",
    detailedDescription: "Detailed nightly summary: lessons completed, cash vs card breakdown, cancellations, no-shows, mileage, and week-over-week comparison. Download as PDF for your records.",
    category: "Reports & Insights",
  },
];
