/**
 * Lucide → native emoji map for the instructor app.
 * Use via the `<Emoji>` component or via primitives that accept an emoji prop.
 * Icons not in this map fall back to their Lucide rendering.
 */
export const ICON_EMOJI_MAP: Record<string, string> = {
  // Activity / scheduling
  Briefcase: "💼",
  MessageSquare: "💬",
  MessageCircle: "💬",
  Mail: "📧",
  Mails: "📨",
  Inbox: "📥",
  Bell: "🔔",
  BellRing: "🔔",
  ClipboardCheck: "📋",
  ClipboardList: "📋",
  Clipboard: "📋",
  CalendarPlus: "📅",
  CalendarDays: "📅",
  CalendarCheck: "📅",
  CalendarClock: "📅",
  CalendarRange: "📅",
  Calendar: "📅",
  Clock: "⏰",
  Timer: "⏱️",
  AlarmClock: "⏰",
  History: "🕘",

  // People / pupils
  User: "👤",
  Users: "👥",
  UserPlus: "🧑",
  UserCheck: "✅",
  GraduationCap: "🎓",
  Baby: "👶",
  Heart: "❤️",
  HeartHandshake: "🤝",
  Handshake: "🤝",
  Smile: "😊",
  ThumbsUp: "👍",

  // Money
  PoundSterling: "💷",
  DollarSign: "💵",
  Euro: "💶",
  Wallet: "👛",
  CreditCard: "💳",
  Receipt: "🧾",
  Calculator: "🧮",
  Gift: "🎁",
  Banknote: "💵",
  Coins: "🪙",
  PiggyBank: "🐷",
  TrendingUp: "📈",
  TrendingDown: "📉",
  BarChart: "📊",
  BarChart2: "📊",
  BarChart3: "📊",
  LineChart: "📈",
  PieChart: "🥧",

  // Vehicle / road
  Car: "🚗",
  CarFront: "🚗",
  Truck: "🚚",
  Bike: "🚲",
  Fuel: "⛽",
  ParkingCircle: "🅿️",
  Construction: "🚧",
  TrafficCone: "🚧",
  Route: "🛣️",
  Navigation: "🧭",
  Compass: "🧭",
  Map: "🗺️",
  MapPin: "📍",
  MapPinned: "📍",
  Radio: "📡",
  Satellite: "🛰️",
  Signal: "📶",

  // Status / alerts
  CheckCircle: "✅",
  CheckCircle2: "✅",
  Check: "✅",
  CheckSquare: "☑️",
  XCircle: "❌",
  AlertCircle: "⚠️",
  AlertTriangle: "⚠️",
  AlertOctagon: "🛑",
  ShieldAlert: "🛡️",
  Shield: "🛡️",
  ShieldCheck: "🛡️",
  Info: "ℹ️",
  HelpCircle: "❓",
  Sparkles: "✨",
  Star: "⭐",
  Trophy: "🏆",
  Medal: "🏅",
  Award: "🏅",
  Flame: "🔥",
  Zap: "⚡",
  Target: "🎯",
  Flag: "🚩",

  // Communication
  Phone: "📞",
  PhoneCall: "📞",
  PhoneIncoming: "📞",
  PhoneOutgoing: "📞",
  Smartphone: "📱",
  Send: "📤",
  Share: "📤",
  Share2: "📤",
  AtSign: "📧",

  // Files / data
  FileText: "📄",
  File: "📄",
  Files: "📑",
  FolderOpen: "📂",
  Folder: "📁",
  Image: "🖼️",
  Camera: "📷",
  Video: "📹",
  Mic: "🎤",
  MicOff: "🎤",
  Music: "🎵",
  Headphones: "🎧",
  Printer: "🖨️",
  Download: "⬇️",
  Upload: "⬆️",
  Save: "💾",
  Bookmark: "🔖",
  BookOpen: "📖",
  Book: "📚",
  Library: "📚",
  Pencil: "✏️",
  Edit: "✏️",
  Edit2: "✏️",
  Edit3: "✏️",
  PenTool: "🖊️",
  Trash: "🗑️",
  Trash2: "🗑️",

  // Navigation / common UI
  Home: "🏠",
  Search: "🔍",
  Settings: "⚙️",
  Settings2: "⚙️",
  Cog: "⚙️",
  Wrench: "🔧",
  Tool: "🛠️",
  Plus: "➕",
  Minus: "➖",
  PlusCircle: "➕",
  Lock: "🔒",
  Unlock: "🔓",
  Key: "🔑",
  Eye: "👁️",
  EyeOff: "🙈",
  Power: "⏻",
  LogOut: "👋",
  LogIn: "👋",

  // Misc
  Sun: "☀️",
  Moon: "🌙",
  CloudRain: "🌧️",
  Cloud: "☁️",
  Snowflake: "❄️",
  Umbrella: "☂️",
  Coffee: "☕",
  Cake: "🎂",
  PartyPopper: "🎉",
  Rocket: "🚀",
  Lightbulb: "💡",
  Globe: "🌐",
  Building: "🏢",
  Building2: "🏢",
  School: "🏫",
  Store: "🏪",
  QrCode: "🔳",
  ScanLine: "📲",
  Tag: "🏷️",
  Tags: "🏷️",
  Filter: "🔽",
  SortAsc: "🔼",
  SortDesc: "🔽",
  RefreshCw: "🔄",
  RefreshCcw: "🔄",
  RotateCw: "🔄",
  Repeat: "🔁",
  Link: "🔗",
  Link2: "🔗",
  Paperclip: "📎",
  Pin: "📌",
  PinOff: "📌",
  ListChecks: "📋",
  List: "📋",
  LayoutGrid: "🔲",
  Grid3X3: "🔲",
  Activity: "📊",
  Gauge: "⏱️",
  Battery: "🔋",
  Wifi: "📶",
  Bluetooth: "📶",
};

export function getEmojiFor(name: string): string | undefined {
  return ICON_EMOJI_MAP[name];
}
