export interface TheoryQuestion {
  id: number;
  question: string;
  options: string[];
  correct: number;
  category: 'road-signs' | 'rules' | 'hazards' | 'vehicle-safety';
  explanation: string;
}

export const THEORY_CATEGORIES = [
  { id: 'road-signs' as const, label: 'Road Signs' },
  { id: 'rules' as const, label: 'Rules of the Road' },
  { id: 'hazards' as const, label: 'Hazard Awareness' },
  { id: 'vehicle-safety' as const, label: 'Vehicle Safety' },
];

export const THEORY_QUESTIONS: TheoryQuestion[] = [
  // Road Signs (15 questions)
  { id: 1, question: "What does a circular traffic sign with a blue background indicate?", options: ["Warning", "Prohibition", "Positive instruction", "Information"], correct: 2, category: 'road-signs', explanation: "Circular signs with a blue background give positive (mandatory) instructions, such as 'turn left' or 'minimum speed'." },
  { id: 2, question: "What does a triangular road sign indicate?", options: ["Give information", "Give orders", "Give warnings", "Give directions"], correct: 2, category: 'road-signs', explanation: "Triangular signs warn you of hazards ahead, such as bends, junctions, or crossroads." },
  { id: 3, question: "What does a circular sign with a red border mean?", options: ["Warning", "Prohibition or restriction", "Information", "Direction"], correct: 1, category: 'road-signs', explanation: "Circular signs with a red border tell you what you must NOT do. For example, no entry or speed limits." },
  { id: 4, question: "What does a brown sign indicate?", options: ["Primary route", "Motorway", "Tourist attraction", "Temporary hazard"], correct: 2, category: 'road-signs', explanation: "Brown signs give directions to tourist attractions and places of interest." },
  { id: 5, question: "What do chevron signs on the road indicate?", options: ["Speed limit change", "Sharp bend ahead", "Road narrows", "Crossroads ahead"], correct: 1, category: 'road-signs', explanation: "Chevron signs are placed at sharp bends to help guide you safely around the curve." },
  { id: 6, question: "A flashing amber signal at a pelican crossing means:", options: ["Stop", "Get ready to go", "Give way to pedestrians on the crossing", "You have right of way"], correct: 2, category: 'road-signs', explanation: "A flashing amber means give way to any pedestrians still on the crossing, but you may proceed if the crossing is clear." },
  { id: 7, question: "What does a green arrow on a traffic light mean?", options: ["You may go only in the direction shown", "The road ahead is clear", "Traffic lights are about to change", "Give way to oncoming traffic"], correct: 0, category: 'road-signs', explanation: "A green arrow filter light means you may proceed in the direction shown, regardless of other lights." },
  { id: 8, question: "What shape is a 'STOP' sign?", options: ["Circular", "Triangular", "Octagonal", "Rectangular"], correct: 2, category: 'road-signs', explanation: "The STOP sign is the only octagonal (8-sided) sign used on UK roads, making it instantly recognisable." },
  { id: 9, question: "What does a sign showing two arrows pointing in opposite directions mean?", options: ["Two-way traffic", "Road narrows", "Dual carriageway ends", "Overtaking allowed"], correct: 0, category: 'road-signs', explanation: "This triangular warning sign tells you that traffic flows in both directions ahead." },
  { id: 10, question: "What do white lines along the centre of the road mean?", options: ["Edge of the road", "No parking zone", "Hazard warning", "Lane or road division"], correct: 3, category: 'road-signs', explanation: "White centre lines divide the road and separate traffic flowing in different directions." },
  { id: 11, question: "Double white lines where the line nearest you is solid mean:", options: ["You may overtake if safe", "You must not cross or straddle them", "Traffic can only travel one way", "Parking is not allowed"], correct: 1, category: 'road-signs', explanation: "A solid white line nearest to you means you must not cross or straddle it except in specific circumstances (e.g., entering premises)." },
  { id: 12, question: "What does a national speed limit sign look like?", options: ["Blue circle with white number", "Red circle with black number", "White circle with black diagonal line", "Green rectangle with white number"], correct: 2, category: 'road-signs', explanation: "The national speed limit sign is a white circle with a black diagonal stripe through it." },
  { id: 13, question: "What does a red cross above a motorway lane mean?", options: ["Lane is clear", "Speed limit applies", "Do not use this lane", "Caution ahead"], correct: 2, category: 'road-signs', explanation: "A red cross means the lane is closed. You must not drive in it." },
  { id: 14, question: "What does a 'clearway' sign mean?", options: ["No parking at any time", "Clear weather expected", "Road is clear of traffic", "No speed limit"], correct: 0, category: 'road-signs', explanation: "A clearway sign means stopping is not permitted at any time on the main carriageway." },
  { id: 15, question: "Zigzag white lines near a crossing mean:", options: ["Speed bumps ahead", "No overtaking and no parking", "Cycle lane", "Rumble strips ahead"], correct: 1, category: 'road-signs', explanation: "You must not park or overtake on zigzag lines near a pedestrian crossing." },

  // Rules of the Road (15 questions)
  { id: 16, question: "What is the national speed limit for cars on a single carriageway?", options: ["50 mph", "60 mph", "70 mph", "40 mph"], correct: 1, category: 'rules', explanation: "The national speed limit on a single carriageway is 60 mph for cars." },
  { id: 17, question: "What is the speed limit on a motorway for cars?", options: ["60 mph", "80 mph", "70 mph", "50 mph"], correct: 2, category: 'rules', explanation: "The speed limit on a motorway is 70 mph unless signs indicate otherwise." },
  { id: 18, question: "What is the national speed limit on a dual carriageway?", options: ["50 mph", "60 mph", "70 mph", "80 mph"], correct: 2, category: 'rules', explanation: "The national speed limit on a dual carriageway is 70 mph for cars." },
  { id: 19, question: "When must you use your headlights?", options: ["Only at night", "When visibility is seriously reduced", "Only in fog", "Only when it's raining"], correct: 1, category: 'rules', explanation: "You must use headlights when visibility is seriously reduced, generally when you cannot see more than 100 metres." },
  { id: 20, question: "What is the legal minimum tread depth for car tyres?", options: ["1mm", "1.6mm", "2mm", "3mm"], correct: 1, category: 'rules', explanation: "The legal minimum tread depth is 1.6mm across the central three-quarters of the tyre, around its entire circumference." },
  { id: 21, question: "At a roundabout, you should give way to traffic from:", options: ["The left", "The right", "Straight ahead", "Behind you"], correct: 1, category: 'rules', explanation: "At a roundabout, you must give way to traffic approaching from your right unless road markings or signs indicate otherwise." },
  { id: 22, question: "When can you use a bus lane?", options: ["Never", "Only outside its hours of operation", "Anytime if turning left", "Only if the road is empty"], correct: 1, category: 'rules', explanation: "You may use a bus lane outside its hours of operation. Check the sign for the times it operates." },
  { id: 23, question: "What should you do at a box junction with yellow cross-hatching?", options: ["Only enter if your exit is clear", "Always give way", "Stop and wait", "Enter only if turning right"], correct: 0, category: 'rules', explanation: "You must not enter a box junction unless your exit is clear. The exception is when turning right and only oncoming traffic is preventing you." },
  { id: 24, question: "What is the stopping distance at 70mph in good conditions?", options: ["53 metres", "73 metres", "96 metres", "120 metres"], correct: 2, category: 'rules', explanation: "At 70 mph: thinking distance (21m) + braking distance (75m) = 96 metres total." },
  { id: 25, question: "When may you reverse from a side road into a main road?", options: ["When safe to do so", "Only during daylight", "Never", "Only on quiet roads"], correct: 2, category: 'rules', explanation: "You should never reverse from a side road into a main road. It's dangerous because your view of main road traffic is restricted." },
  { id: 26, question: "What is the two-second rule?", options: ["Wait 2 seconds at junctions", "Keep at least 2 seconds behind the vehicle ahead", "Flash headlights for 2 seconds", "Signal for 2 seconds before turning"], correct: 1, category: 'rules', explanation: "The two-second rule helps maintain a safe following distance. In wet conditions, double it to four seconds." },
  { id: 27, question: "What is the drink-drive limit for a standard breath test in England?", options: ["25 micrograms per 100ml", "35 micrograms per 100ml", "50 micrograms per 100ml", "80 micrograms per 100ml"], correct: 1, category: 'rules', explanation: "The legal breath alcohol limit in England and Wales is 35 micrograms of alcohol per 100 millilitres of breath." },
  { id: 28, question: "At what age can a passenger travel in the front seat without a seatbelt?", options: ["12 years", "14 years", "16 years", "There is no age — all must wear one"], correct: 1, category: 'rules', explanation: "From age 14, passengers are responsible for wearing their own seatbelt. Under 14, the driver is responsible." },
  { id: 29, question: "When should you use your fog lights?", options: ["Whenever it's dark", "When visibility is below 200m", "When visibility is below 100m", "In heavy rain"], correct: 2, category: 'rules', explanation: "You must only use fog lights when visibility is seriously reduced, generally below 100 metres. Using them at other times is illegal." },
  { id: 30, question: "What is the speed limit in a built-up area unless signs say otherwise?", options: ["20 mph", "30 mph", "40 mph", "50 mph"], correct: 1, category: 'rules', explanation: "The default speed limit in built-up areas (those with street lighting) is 30 mph." },

  // Hazard Awareness (12 questions)
  { id: 31, question: "What should you do if you see a horse and rider ahead?", options: ["Sound your horn to warn them", "Slow down and give plenty of room", "Flash your headlights", "Maintain your speed"], correct: 1, category: 'hazards', explanation: "Slow down, give them plenty of room, and pass them slowly. Horses can be easily frightened by vehicles." },
  { id: 32, question: "You're driving in fog. What should you do?", options: ["Use full beam headlights", "Stay close to the car in front", "Use dipped headlights and reduce speed", "Use only sidelights"], correct: 2, category: 'hazards', explanation: "Use dipped headlights (not full beam, which reflects off the fog) and reduce your speed. Use fog lights if visibility is below 100m." },
  { id: 33, question: "What is 'aquaplaning'?", options: ["Driving through a puddle", "Your tyres losing contact with the road due to water", "Skidding on ice", "Your windscreen misting up"], correct: 1, category: 'hazards', explanation: "Aquaplaning happens when water builds up between your tyres and the road surface, causing loss of grip and steering." },
  { id: 34, question: "What is the main cause of skidding?", options: ["Faulty brakes", "The driver", "Wet roads", "Worn tyres"], correct: 1, category: 'hazards', explanation: "Skidding is almost always caused by the driver asking too much of the vehicle for the conditions — braking, accelerating or steering too harshly." },
  { id: 35, question: "You see brake lights ahead on a motorway. What should you do?", options: ["Overtake on the left", "Slow down and be prepared to stop", "Flash your headlights", "Change lanes immediately"], correct: 1, category: 'hazards', explanation: "Brake lights ahead may indicate slowing or stopped traffic. Reduce speed and be ready to stop. Consider using hazard warning lights briefly to warn drivers behind." },
  { id: 36, question: "Where are you most likely to encounter black ice?", options: ["On main roads", "On shaded or sheltered areas", "On roundabouts", "On well-lit streets"], correct: 1, category: 'hazards', explanation: "Black ice forms on shaded areas, under bridges and trees, where the road temperature stays lower. It's almost invisible." },
  { id: 37, question: "What should you do if a child runs out between parked cars?", options: ["Sound your horn", "Flash your lights", "Be ready to stop — always anticipate this", "Swerve to avoid them"], correct: 2, category: 'hazards', explanation: "Always expect children to run out unexpectedly near parked cars, schools, and residential areas. Reduce speed and be ready to stop." },
  { id: 38, question: "How can you identify areas of road with a greater crash risk?", options: ["They have rumble strips", "Warning signs and road markings give clues", "The road surface is darker", "There are more lampposts"], correct: 1, category: 'hazards', explanation: "Warning signs (bends, junctions, crossings) and road markings alert you to potential hazard areas." },
  { id: 39, question: "What effect does tiredness have on your driving?", options: ["It improves concentration", "It slows reaction time and reduces awareness", "It has no effect if you keep windows open", "It only matters at night"], correct: 1, category: 'hazards', explanation: "Tiredness seriously affects your ability to concentrate, react, and judge situations. Take regular breaks on long journeys." },
  { id: 40, question: "A car is overtaking you. What should you do?", options: ["Speed up to prevent them", "Slow down slightly and maintain your position", "Move to the right", "Flash your headlights"], correct: 1, category: 'hazards', explanation: "When being overtaken, maintain a steady course and speed, or slow down slightly to help them pass safely." },
  { id: 41, question: "When driving on a wet road, how much longer can stopping distances be?", options: ["The same", "Twice as long", "Three times as long", "Ten times as long"], correct: 1, category: 'hazards', explanation: "In wet conditions, stopping distances can be at least double those in dry conditions." },
  { id: 42, question: "What should you do if your vehicle starts to aquaplane?", options: ["Brake firmly", "Ease off the accelerator gently", "Turn the steering wheel", "Accelerate to regain grip"], correct: 1, category: 'hazards', explanation: "If you aquaplane, ease off the accelerator gently. Don't brake or steer sharply as this could cause a skid." },

  // Vehicle Safety (13 questions)
  { id: 43, question: "How often should you check your tyre pressures?", options: ["Once a year", "At every service", "At least once a week", "Monthly"], correct: 2, category: 'vehicle-safety', explanation: "Check tyre pressures at least weekly and before long journeys. Use the manufacturer's recommended pressures found in the handbook or door pillar." },
  { id: 44, question: "Where would you find your car's recommended tyre pressure?", options: ["On the tyres themselves", "In the owner's manual / door pillar", "On the dashboard", "At the petrol station"], correct: 1, category: 'vehicle-safety', explanation: "Recommended tyre pressures are in the vehicle handbook and often on a sticker on the driver's door pillar or fuel cap." },
  { id: 45, question: "What is the purpose of the head restraint?", options: ["For comfort on long journeys", "To help you see behind", "To reduce neck injury in a rear collision", "To support the seat"], correct: 2, category: 'vehicle-safety', explanation: "Head restraints reduce the risk of whiplash injuries in a rear-end collision. They should be adjusted to the correct height." },
  { id: 46, question: "How should you check your brake lights are working?", options: ["Ask someone to stand behind while you press the brake", "You can see them in the dashboard", "Listen for a click", "They check themselves automatically"], correct: 0, category: 'vehicle-safety', explanation: "The easiest way is to ask someone to check while you press the brake pedal, or use a reflection in a wall/window." },
  { id: 47, question: "When should you use hazard warning lights?", options: ["When parked illegally", "When your vehicle is temporarily obstructing traffic or to warn of danger", "When driving slowly", "When towing"], correct: 1, category: 'vehicle-safety', explanation: "Use hazard lights when your vehicle is stationary and temporarily obstructing traffic, or on a motorway to warn of a hazard ahead." },
  { id: 48, question: "What should you do before starting a journey in freezing conditions?", options: ["Just drive slowly", "Clear all windows of ice and check lights", "Only clear the driver's window", "Start the engine and wait 30 minutes"], correct: 1, category: 'vehicle-safety', explanation: "Before driving in freezing conditions, clear ALL windows of ice/snow, check lights, mirrors, and that your screenwash is topped up with anti-freeze." },
  { id: 49, question: "What colour is engine coolant warning light?", options: ["Green", "Blue", "Red", "Amber"], correct: 2, category: 'vehicle-safety', explanation: "The engine coolant warning light is red. If it comes on while driving, stop safely as soon as possible — the engine may be overheating." },
  { id: 50, question: "How do you check your power steering is working?", options: ["Listen for a whining noise", "Turn the steering wheel just after starting — it should feel light", "Check the dipstick", "Press the brake pedal"], correct: 1, category: 'vehicle-safety', explanation: "Gently turn the steering wheel just after starting the engine. If the power steering is working, the wheel should turn easily." },
  { id: 51, question: "What fluid would you find in the brake reservoir?", options: ["Engine oil", "Brake fluid / hydraulic fluid", "Water", "Power steering fluid"], correct: 1, category: 'vehicle-safety', explanation: "The brake reservoir contains hydraulic brake fluid. Check the level regularly — it should be between the minimum and maximum marks." },
  { id: 52, question: "Anti-lock brakes (ABS) help you to:", options: ["Stop in a shorter distance", "Maintain steering control while braking hard", "Brake without using the pedal", "Drive faster safely"], correct: 1, category: 'vehicle-safety', explanation: "ABS prevents the wheels from locking during emergency braking, allowing you to maintain steering control." },
  { id: 53, question: "What should you check before a long journey?", options: ["Oil, water, tyres, and fuel", "Just the fuel", "Only the sat nav", "The radio works"], correct: 0, category: 'vehicle-safety', explanation: "Before a long journey, check FLOWERY: Fuel, Lights, Oil, Water, Electrics, Rubber (tyres), Yourself (fitness to drive)." },
  { id: 54, question: "Where is the catalytic converter found?", options: ["In the engine", "In the exhaust system", "In the gearbox", "In the fuel tank"], correct: 1, category: 'vehicle-safety', explanation: "The catalytic converter is in the exhaust system. It reduces toxic emissions by converting harmful gases into less harmful substances." },
  { id: 55, question: "What does the oil pressure warning light look like?", options: ["A thermometer", "An oil can", "A battery", "A spanner"], correct: 1, category: 'vehicle-safety', explanation: "The oil pressure warning light looks like an oil can (genie lamp shape). If it comes on while driving, stop and check oil level immediately." },
];

export function getRandomQuestions(count: number, category?: string): TheoryQuestion[] {
  let pool = category
    ? THEORY_QUESTIONS.filter(q => q.category === category)
    : [...THEORY_QUESTIONS];
  
  // Fisher-Yates shuffle
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  
  return pool.slice(0, count);
}
