export const SECTION_TITLES: Record<string, string> = {
  profile:           "Profile & photo",
  security:          "Login & security",
  notifications:     "Notifications",
  vehicle:           "Vehicle & credentials",
  hours:             "Working hours",
  rates:             "Rates & coverage",
  lessons:           "Lesson types & durations",
  "how-book":        "How pupils book",
  cancellation:      "Cancellation policy",
  waiting:           "Waiting list & fill gaps",
  "payment-methods": "Payment methods",
  payout:            "Payout account",
  vat:               "VAT & invoicing",
  swap:              "Test swap settings",
  help:              "Help & support",
  privacy:           "Data & privacy",
};

export const SECTION_SUBTITLES: Record<string, string> = {
  profile:           "How learners and Drive365 identify you",
  security:          "Password, biometrics and two-factor auth",
  notifications:     "Control when and how you receive alerts",
  vehicle:           "Your car, licence number and DVSA credentials",
  hours:             "When you're available to teach",
  rates:             "Your prices, radius and postcode coverage",
  lessons:           "Intensive, semi-intensive, weekly and custom",
  "how-book":        "Instant booking, deposits and requests",
  cancellation:      "Notice periods, fees and refund rules",
  waiting:           "Manage your waiting list and auto-fill gaps",
  "payment-methods": "Cards, Klarna and bank transfer options",
  payout:            "Where your earnings are sent",
  vat:               "VAT registration and invoice templates",
  swap:              "Test swap network and notification settings",
  help:              "FAQs, contact Drive365 and leave feedback",
  privacy:           "Data export, account deletion and GDPR rights",
};
