import * as React from 'npm:react@18.3.1'
import {
  Body, Container, Head, Heading, Html, Preview, Text, Button, Section, Hr,
} from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

interface Props {
  pupilName?: string
  invoiceNumber?: string
  totalAmount?: string
  issueDate?: string
  downloadUrl?: string
  instructorName?: string
}

const Email = ({ pupilName, invoiceNumber, totalAmount, issueDate, downloadUrl, instructorName }: Props) => (
  <Html lang="en" dir="ltr">
    <Head />
    <Preview>Your driving lesson invoice {invoiceNumber}</Preview>
    <Body style={{ backgroundColor: '#ffffff', fontFamily: 'Arial, sans-serif', margin: 0 }}>
      <Container style={{ padding: '24px', maxWidth: '560px' }}>
        <Heading style={{ fontSize: '20px', color: '#111' }}>Invoice {invoiceNumber}</Heading>
        <Text>Hi {pupilName || 'there'},</Text>
        <Text>
          Here is your driving lesson invoice from {instructorName || 'your instructor'} for {issueDate}.
        </Text>
        <Section style={{ background: '#F4F7F6', padding: '16px', borderRadius: '12px', margin: '16px 0' }}>
          <Text style={{ margin: 0 }}><strong>Invoice:</strong> {invoiceNumber}</Text>
          <Text style={{ margin: 0 }}><strong>Date:</strong> {issueDate}</Text>
          <Text style={{ margin: 0 }}><strong>Total:</strong> £{totalAmount}</Text>
        </Section>
        {downloadUrl && (
          <Button href={downloadUrl} style={{ background: '#2D3FE7', color: '#fff', padding: '12px 20px', borderRadius: '10px', textDecoration: 'none' }}>
            Download PDF
          </Button>
        )}
        <Hr style={{ margin: '24px 0' }} />
        <Text style={{ fontSize: '12px', color: '#666' }}>
          This is an automatic invoice generated by your driving instructor's booking system.
        </Text>
      </Container>
    </Body>
  </Html>
)

export const template = {
  component: Email,
  subject: (data: any) => `Your driving lesson invoice — ${data?.invoiceNumber ?? ''}`.trim(),
  displayName: 'Auto Invoice',
  previewData: {
    pupilName: 'Jane',
    invoiceNumber: 'INV-2026-0001',
    totalAmount: '90.00',
    issueDate: '2026-06-10',
    downloadUrl: 'https://example.com/invoice.pdf',
    instructorName: 'John',
  },
} satisfies TemplateEntry
