-- Add comprehensive UK DVSA driving test centres (inserting only if not exists by name)
INSERT INTO public.test_centres (name, address, postcode) VALUES
-- A
('Aberdeen North', 'Cloverhill Road, Bridge of Don', 'AB23 8FE'),
('Abergavenny', 'Station Road', 'NP7 5HT'),
('Airdrie', '7 Aitchison Street, Sword Street', 'ML6 0DA'),
('Ashford (Kent)', 'Ground Floor, Civic Centre, Tannery Lane', 'TN23 1PL'),
('Aylesbury', 'Unit 9 Ground Floor, Bell Business Park', 'HP19 8JR'),
-- B
('Bala', 'Unit 4, Penllyn Workshops', 'LL23 7SP'),
('Ballater', 'The Lecture Room, Ballater Fire Station Anderson Road', 'AB35 5QW'),
('Banbury', '3 West Bar Street', 'OX16 9SD'),
('Banff', 'C/O Dept. of Employment, 23/25 Castle Street', 'AB45 1DJ'),
('Bangor', 'Llandygai Industrial Estate, Llandygai', 'LL57 4YH'),
('Barking', '84 Tanner Street', 'IG11 8QF'),
('Barnet', 'Raydean House 15/17 Western Parade', 'EN5 1AD'),
('Barnsley', 'West Road', 'S75 2DH'),
('Barnstaple', 'Unit 1A, Benning Court, Pottington Industrial Estate', 'EX31 1AB'),
('Barrow-in-Furness', 'Trinity Enterprise Centre, Unit 11 Ironworks Road', 'LA14 2PN'),
('Basildon', 'Paycocke Road', 'SS14 3JS'),
('Basingstoke', 'Brighton Hill Centre', 'RG22 4LR'),
('Bathgate', '74 Glasgow Road', 'EH48 2AG'),
('Bedford', 'Portman House, 59/63 Goldington Road', 'MK40 3LT'),
('Belvedere', '33 Woolwich Road', 'DA17 5EE'),
('Bettyhill', 'C/O Bettyhill Post Office', 'KW14 7SP'),
('Beverley', 'Old Beck Road, off Groveshill Road', 'HU17 0JG'),
('Birmingham (Cocks Moor Woods)', 'Cocks Moors Woods Leisure Centre, Alcester Road', 'B14 6ER'),
('Birmingham (Kings Heath)', '955 Alcester Road South', 'B14 5JA'),
('Birmingham (Kingstanding)', '205 Birdbrook Road, Kingstanding', 'B44 9UL'),
('Birmingham (Shirley)', '401 Stratford Road, Shirley, Solihull', 'B90 4AA'),
('Birmingham (Sutton Coldfield)', '110/116 Boldmere Road, Sutton Coldfield', 'B73 5UB'),
('Birmingham Garretts Green', 'Granby Avenue, Garretts Green', 'B33 0TJ'),
('Bishops Stortford', 'South Road', 'CM23 3LD'),
('Blackburn', 'Blackburn Interchange, Commercial Road, Darwen', 'BB3 0DB'),
('Bletchley', 'Block 4 Government Buildings, Wilton Avenue', 'MK3 6DH'),
('Blyth', 'Unit 3 Sextant House, Freehold Street', 'NE24 3BA'),
('Bodmin', 'Units 32-36, Walker Lines Offices, Beatrice Road', 'PL31 1RD'),
('Bolton', 'Weston Street', 'BL3 2AW'),
('Borehamwood', 'Unit 1 Stirling Court, Stirling Way', 'WD6 2BT'),
('Boston', 'Unit 2 Plot 3, Redstone Industrial Estate, Spalding Road', 'PE21 8AL'),
('Bournemouth', '21/23 Gillam Road, Northbourne', 'BH10 6BW'),
('Bradford (Thornbury)', 'The Courtyard, Midpoint, Thornbury', 'BD3 7AY'),
('Bradford (Heaton)', '15 Farfield Street, Heaton', 'BD9 5AS'),
('Brecon', 'Camden Road', 'LD3 7RY'),
('Brentwood', '89 Warley Hill', 'CM14 5JN'),
('Bridgend', 'Crown Buildings, Angel Street', 'CF31 4AD'),
('Bridlington', 'Crown Buildings, Quay Road', 'YO16 4LY'),
('Bristol (Avonmouth)', 'Unit M6, Cabot Park, Merebank Road', 'BS11 8AQ'),
('Bristol (Southmead)', '2 Concord Drive, Southmead', 'BS10 6PZ'),
('Bristol (Kingswood)', 'Siston Centre, Kingswood', 'BS15 4GQ'),
('Buckie', 'The Fire Station, East Cathcart Street', 'AB56 1QJ'),
('Burton on Trent', 'Wellington Road', 'DE14 2TG'),
('Bury', 'Smith Street', 'BL9 6HH'),
('Bury St Edmunds', 'Tritron House, St Andrews Street North', 'IP33 1TJ'),
-- C
('Callander', 'Burgh Chambers, South Church Street', 'FK17 8BN'),
('Cambridge (Brookmount Court)', 'Units A & B Brookmount Court, Kirkwood Road', 'CB4 2QH'),
('Cambridge (Chesterton Road)', '73/79 Chesterton Road', 'CB4 3AP'),
('Cambridge (Cowley Road)', 'Cowley Road', 'CB4 0DT'),
('Campbeltown', 'Crown Buildings, Hall Street', 'PA28 6BD'),
('Cannock', 'Suite 3, Commerce House, Ridings Park, Hawks Green Lane', 'WS11 7FJ'),
('Canterbury', '25 New Dover Road', 'CT1 3AS'),
('Cardiff (Llanishen)', 'Thornbury House, Unit 11 Lambourne Crescent, Cardiff Business Park', 'CF14 5GF'),
('Cardiff (Fairwater)', '30 Norbury Road, Fairwater', 'CF5 3AU'),
('Carlisle', 'Port Road Business Park, Port Road', 'CA2 7AF'),
('Carmarthen', 'Ty Myrddin, Crown Building, Old Station Road', 'SA31 1GS'),
('Castle Douglas', 'Carlingwark Cottage, Buchan Street', 'DG7 1TH'),
('Cheetham Hill', 'Alderglen Road, Cheetham, Manchester', 'M8 0TD'),
('Chelmsford', 'Hanbury Road, Widford Industrial Estate', 'CM1 3DR'),
('Cheltenham', 'Bishopsgate House, 94 All Saints Road', 'GL52 2HQ'),
('Chertsey', 'Unit 4, The Forum, Hanworth Industrial Estate', 'KT16 9RN'),
('Chester', 'Front Parade Ground, Saighton Camp, Huntington', 'CH3 5UE'),
('Chesterfield', 'Bus Garage Approach Road, Stonegravels', 'S41 7LF'),
('Chichester', 'Wyman House, Shopwhyke Road', 'PO20 2AA'),
('Chingford', 'Doric House, 128 Station Road', 'E4 6AD'),
('Chorley', 'Rossall Road', 'PR6 0BT'),
('Clacton-on-Sea', '103/105 Carnarvon Road', 'CO15 6PR'),
('Colchester', 'Grange Way', 'CO2 8HF'),
('Coventry (Bayton Road)', '42 Bayton Road', 'CV7 9EJ'),
('Crawley', 'Unit 2 The Pavillions, Brighton Road, Pease Pottage', 'RH11 9BJ'),
('Crewe', '6 Nile Street', 'CW2 7LL'),
('Crieff', 'Crieff Fire Station, Broich Road', 'PH7 3SB'),
('Croydon', '111 Canterbury Road', 'CR0 3HH'),
('Cumnock', 'The Town Hall, Hall Terrace', 'KA18 1BY'),
-- D
('Darlington', 'Yarm Road, High Point Business Park', 'DL1 4PW'),
('Derby (Sinfin Lane)', 'Ordnance Cottage, Sinfin Lane', 'DE24 9GL'),
('Doncaster', 'Shaftesbury Avenue, Intake', 'DN2 6DT'),
('Dorchester', 'Government Buildings, Prince of Wales Road', 'DT1 1PU'),
('Dumbarton', 'C/O The Benefits Agency, 15 Meadowbank Street', 'G82 1SJ'),
('Dumfries', '161 Brooms Road', 'DG1 2SH'),
('Dundee', 'Block 23B, Kilspindie Place, Dunsinane Industrial Estate', 'DD2 3QH'),
('Dunfermline', 'Estantia House, Pitreavie Drive', 'KY11 8UH'),
('Dunoon', 'C/O The Job Centre, George Street', 'PA23 8AR'),
-- E
('Eastbourne', 'Unit G3 Hawthorn Road, Hampden Park', 'BN22 9AX'),
('Edinburgh (Currie)', '196 Lanark Road West, Currie', 'EH14 5NY'),
('Edinburgh (Musselburgh)', 'Inveresk Road, Musselburgh', 'EH21 7BP'),
('Elgin', 'Tyock Industrial Estate, Elgin', 'IV30 1XY'),
('Elswick', 'Scotswood Road, Elswick, Newcastle upon Tyne', 'NE4 7AR'),
('Enfield', 'Unit 7 Meridian Business Park, Mollison Avenue', 'EN3 7SR'),
('Erith', 'Erith Sports Centre, Avenue Road', 'DA8 3AT'),
('Exeter', '60 Cowick Street, St Thomas', 'EX4 1AP'),
-- F
('Failsworth', 'Unit 6, Victoria Trading Estate, Rochdale Road', 'M35 9DA'),
('Falkirk', 'Unit 21 Central Business Park, Carrongrange Avenue', 'FK1 1ST'),
('Farnborough', '134 Farnborough Road', 'GU14 6TD'),
('Forfar', 'Orchardbank Business Park, Arbroath Road', 'DD8 1AR'),
('Fort William', 'Ardblair Road, Caol', 'PH33 7ND'),
-- G
('Galashiels', 'Ladhope Vale', 'TD1 1BS'),
('Garston', 'Unit 8-10, Banks Road', 'L19 8JL'),
('Gillingham (Kent)', '215 Canterbury Street', 'ME7 5XS'),
('Glasgow (Anniesland)', '1115 Crow Road, Anniesland', 'G13 1NP'),
('Glasgow (Baillieston)', '27 Caledonian Road, Baillieston', 'G69 7AZ'),
('Glasgow (Mosspark)', '42 Corkerhill Road, Mosspark', 'G52 1DS'),
('Glasgow (Shieldhall)', '250 Helen Street, Govan', 'G51 3HR'),
('Glenrothes', 'Pentland Court, Saltire Centre', 'KY6 2DA'),
('Gloucester', '78 Stroud Road', 'GL1 5AJ'),
('Goodmayes', 'Birch Terrace, 37 Goodmayes Road', 'IG3 9SZ'),
('Grantham', 'Units 8-9 Grantham Business Park, London Road', 'NG31 6EY'),
('Gravesend', '18 The Grove', 'DA12 1DN'),
('Great Yarmouth', 'Caister Road', 'NR30 4EZ'),
('Greenford', '56 The Broadway', 'UB6 9PH'),
('Greenock', 'James Watt Buildings, 2 Dellingburn Street', 'PA15 4UW'),
('Grimsby', 'Unit 1 Meridian Point, Cleethorpe Road', 'DN31 3TP'),
('Guildford', 'Woodbridge Road', 'GU1 4RD'),
-- H
('Haddington', 'Council Chambers, Court Street', 'EH41 3HA'),
('Halifax', '26/28 Bull Green', 'HX1 2DL'),
('Hamilton', '15 Almada Street', 'ML3 0EY'),
('Harehills', 'Roundhay Road, Harehills, Leeds', 'LS8 5PT'),
('Harlow', 'Harlow Sports Centre, Hammarskjold Road', 'CM20 2JF'),
('Harrogate', '39 East Parade', 'HG1 5LQ'),
('Hartlepool', 'Park Road', 'TS26 9HR'),
('Hastings', '10 Cornwallis Terrace', 'TN34 1EB'),
('Haverfordwest', 'Government Buildings, Winch Lane', 'SA61 1QE'),
('Hayes', 'Pump Lane', 'UB3 3NB'),
('Heckmondwike', 'Hick Lane, Batley', 'WF17 0AA'),
('Hendon', 'Ground Floor, 59/63 Brent Street', 'NW4 2EA'),
('Hereford', 'Station Approach', 'HR1 1BB'),
('Hemel Hempstead', 'Mark Road, Hemel Hempstead Industrial Estate', 'HP2 7DN'),
('High Wycombe', 'Suffield Road', 'HP11 2SZ'),
('Hinckley', 'Unit 1 Wellington Street', 'LE10 0AG'),
('Hornchurch', '96/98 Station Lane', 'RM12 6NB'),
('Horsham', 'Old Holbrook, Horsham', 'RH12 1QD'),
('Huddersfield', '3/5 Old Leeds Road', 'HD1 1RW'),
('Hull', 'Chanterlands Avenue', 'HU5 3TL'),
('Huntingdon', 'St Peters Road', 'PE29 7BN'),
-- I
('Inverness', 'Harbour Road', 'IV1 1UA'),
('Inverurie', 'Thainstone Business Centre, Inverurie', 'AB51 5TB'),
('Ipswich', 'Grimwade Street', 'IP4 1LN'),
('Irvine', 'Unit 3-4, 2 Annick Road, Annick Industrial Estate', 'KA11 4AA'),
('Isle of Mull', 'Craignure Village Hall, Craignure, Isle of Mull', 'PA65 6AY'),
('Isle of Wight (Newport)', 'Unit 2A, Riverway Industrial Estate', 'PO30 5UX'),
('Isleworth', 'London Road', 'TW7 5BX'),
-- K
('Keighley', 'Hanover House, South Street', 'BD21 1AG'),
('Kendal', 'Lakeland Business Park, Lammerside', 'LA9 6NH'),
('Kettering', 'Crown House, Horsemarket', 'NN16 0DE'),
('Kilmarnock', 'Grange Street', 'KA1 2DD'),
('Kings Lynn', 'Unit 3-4, Hardwick Industrial Estate, Hardwick Road', 'PE30 4NA'),
('Kirkcaldy', 'St Clair Street', 'KY1 2BN'),
-- L
('Lanark', 'The Town Hall, High Street', 'ML11 7ES'),
('Lancaster', 'Carnforth Road, Morecambe', 'LA3 2AZ'),
('Leatherhead', 'Town Centre House, The Crescent', 'KT22 8DY'),
('Lee on the Solent', 'Lee on the Solent Enterprise Centre', 'PO13 8FY'),
('Leeds (Horsforth)', 'Unit 1, Grove Lane, Horsforth', 'LS18 5HQ'),
('Leicester (Cannock Street)', 'Cannock Street', 'LE4 7HR'),
('Leicester (Wigston)', 'Cooks Lane, Wigston', 'LE18 3TZ'),
('Letchworth', 'Icknield Way, Letchworth Garden City', 'SG6 1TN'),
('Lewes', 'Unit 3, Barber Business Park, Station Road', 'BN8 4PH'),
('Lincoln', 'Newark Road', 'LN6 8RN'),
('Livingston', '1 Grampian Court, Beveridge Square', 'EH54 6QF'),
('Llandrindod Wells', 'Llanyre, Llandrindod Wells', 'LD1 6DF'),
('Llandudno', 'Ffordd Penrhyn, Mostyn Broadway', 'LL30 1YW'),
('Llanelli', 'Valley Business Park, Morfa Road', 'SA15 2LH'),
('Loughborough', 'Beacon Road', 'LE11 5GW'),
('Louth', 'Fairfield Industrial Estate, Fairfield', 'LN11 0JH'),
('Lowestoft', 'Oban Way', 'NR32 2AD'),
-- M
('Macclesfield', 'Park Lane', 'SK11 6TX'),
('Maidstone', 'Hart Street', 'ME16 8RB'),
('Malton', 'Norton Business Park, Langton Road', 'YO17 9QF'),
('Manchester (East Didsbury)', 'Cavendish Road, East Didsbury', 'M20 1QG'),
('Manchester (Failsworth)', 'Unit 6, Victoria Trading Estate, Rochdale Road', 'M35 9DA'),
('Mansfield', 'Crown Farm Industrial Estate, Station Road', 'NG18 5UP'),
('Melton Mowbray', 'Scalford Road', 'LE13 1JY'),
('Merthyr Tydfil', 'Avenue de Clichy, Pentrebach', 'CF48 4TQ'),
('Middlesbrough', 'Cambridge Road', 'TS5 5NL'),
('Mill Hill', 'Frith Lane', 'NW7 1PS'),
('Mitcham', '343 London Road', 'CR4 4BE'),
('Morden', '255 Central Road', 'SM4 5PQ'),
-- N
('Neath', 'Old Road, Skewen', 'SA10 6ES'),
('Newcastle upon Tyne (Gosforth)', 'Ayton Court, Great North Road, Gosforth', 'NE3 2DT'),
('Newport (Gwent)', 'Malpas Road', 'NP20 5PL'),
('Newry', 'Greenbank Industrial Estate, Rampart Road', 'BT34 2QU'),
('Northampton', 'Northfield Avenue, St James', 'NN5 5HL'),
('Northwich', 'Wincham Lane, Wincham', 'CW9 6DG'),
('Norwich', 'Martineau Lane', 'NR1 2HL'),
('Nottingham (Chilwell)', 'High Road, Chilwell', 'NG9 5EG'),
('Nottingham (Colwick)', 'Private Road No.1, Colwick Industrial Estate', 'NG4 2JT'),
('Nuneaton', '7 Riversley Road', 'CV11 5QT'),
-- O
('Oban', 'Lochavullin Industrial Estate', 'PA34 4PL'),
('Oldbury', 'Portway Road', 'B68 0JH'),
('Oldham', 'Middleton Road', 'OL9 9NY'),
('Orkney', 'Grainbank Stores, Junction Road, Kirkwall', 'KW15 1AW'),
('Oswestry', 'Maes-Y-Clawdd Business Centre, Mile End', 'SY11 2TA'),
-- P
('Paisley', '3 Canal Street', 'PA1 2HD'),
('Peebles', 'Crown Buildings, Rosetta Road', 'EH45 8HG'),
('Pembroke Dock', 'London Road', 'SA72 6TW'),
('Penzance', 'The Studio, Wheal Bal', 'TR18 4QR'),
('Perth', 'Necessity Brae', 'PH2 0PL'),
('Peterborough', 'Ham Lane', 'PE2 5UU'),
('Pinner', 'The Studios, Marsh Road', 'HA5 5LU'),
('Pitlochry', 'Atholl Road', 'PH16 5BX'),
('Plymouth', 'Grosvenor Buildings, Plympton', 'PL7 4JR'),
('Pontefract', 'Stuart Road', 'WF8 4PB'),
('Pontypridd', 'Government Buildings, Sardis Road', 'CF37 1DU'),
('Poole', '25 Hill Street', 'BH15 1NR'),
('Portadown', 'Unit 6, Carn Industrial Estate, Craigavon', 'BT63 5RH'),
('Portsmouth', 'Clarendon Road', 'PO5 2SG'),
('Preston', 'Unit 3 Ringway House, Kellet Road', 'PR2 1HP'),
('Pwllheli', 'The Old Cinema, Y Maes', 'LL53 5HA'),
-- R
('Redditch', 'Kingfisher Drive', 'B98 0LG'),
('Rhyl', 'Brighton Road', 'LL18 3HF'),
('Rochdale', '2 Bamford Road, Heywood', 'OL10 4EB'),
('Rotherham', 'Moorgate Road', 'S60 2AG'),
('Rugby', 'Newbold Road', 'CV21 2LP'),
-- S
('Salford', 'Clarendon Crescent', 'M5 4QE'),
('Salisbury', 'Coldharbour Lane, Harnham', 'SP2 8HH'),
('Scarborough', 'Queen Margarets Road', 'YO11 2LZ'),
('Scunthorpe', 'Kingsway', 'DN15 7LR'),
('Sheffield (Handsworth)', 'Handsworth Road, Handsworth', 'S13 9BY'),
('Shrewsbury', 'Lancaster Road, Harlescott', 'SY1 3NJ'),
('Sidcup', 'Elm Road', 'DA14 6NF'),
('Skegness', 'Wainfleet Road', 'PE25 3QT'),
('Skipton', 'Otley Street', 'BD23 1EW'),
('Slough', 'Farnham Road', 'SL2 1DA'),
('Southampton', 'Empress Road', 'SO14 0JN'),
('Southend-on-Sea', '90 Victoria Avenue', 'SS2 6BT'),
('Southport', '21 Manchester Road', 'PR9 9AF'),
('South Shields', 'Keppel Street', 'NE33 1BJ'),
('Stafford', 'Riverway, Stafford', 'ST16 3TH'),
('St Albans', 'Civic Centre, St Peters Street', 'AL1 3JE'),
('St Helens', 'Boundary Road', 'WA10 2PR'),
('Stevenage', 'Argyle Way', 'SG1 2AD'),
('Stirling', 'Whitehouse Road', 'FK7 7RH'),
('Stockport', 'Wellington Road South', 'SK1 3TS'),
('Stoke-on-Trent', 'Newcastle Street, Tunstall', 'ST6 5EU'),
('Stranraer', 'Lewis Street', 'DG9 7AL'),
('Sunderland', 'Rutland Street', 'SR1 3PZ'),
('Sutton', 'Mulgrave Road', 'SM2 6LE'),
('Swansea', 'Cwm Level Road, Landore', 'SA6 7BH'),
('Swindon', 'Gypsy Lane, Stratton', 'SN2 8AW'),
-- T
('Tamworth', 'Hedging Lane', 'B77 5HF'),
('Taunton', 'Priory Bridge Road', 'TA1 1NP'),
('Telford', 'Euston Way, Town Centre', 'TF3 4LT'),
('Thurso', 'Ormlie Industrial Estate', 'KW14 7QW'),
('Tilbury', 'Montreal Road, Tilbury', 'RM18 7QS'),
('Torquay', 'St Marychurch Road', 'TQ1 4AY'),
('Tottenham', 'Coppetts Road', 'N10 1JJ'),
('Truro', 'New County Hall, Treyew Road', 'TR1 3AY'),
-- U
('Uxbridge', 'Cowley Mill Road', 'UB8 2AD'),
-- W
('Wakefield', 'Thornes Lane', 'WF2 7RF'),
('Walsall', 'Green Lane', 'WS2 7PD'),
('Wanstead', 'Spratt Hall Road', 'E11 2RQ'),
('Warrington', 'Lovely Lane', 'WA5 0LN'),
('Warwick', 'Montague Road', 'CV34 5LW'),
('Wednesbury', 'Walsall Street', 'WS10 9DD'),
('Wellingborough', 'Highfield Road', 'NN8 1HN'),
('West Bromwich', 'Tantany Lane', 'B70 6AQ'),
('Whitby', 'Bagdale', 'YO21 1QL'),
('Widnes', 'Moor Lane', 'WA8 7AQ'),
('Wigan', 'Robin Park Road', 'WN5 0UH'),
('Winchester', 'Alresford Road', 'SO23 0JH'),
('Wolverhampton', 'Bilston Road', 'WV14 0DL'),
('Wood Green', 'High Road', 'N22 6AA'),
('Worcester', 'Padmore Street', 'WR2 5DS'),
('Worksop', 'Hardy Street', 'S80 1QQ'),
('Worthing', 'Broadwater Road', 'BN14 8HJ'),
('Wrexham', 'Crown Buildings, Chester Road', 'LL13 8BG'),
-- Y
('Yeading', 'Glencoe Road', 'UB4 9SD'),
('Yeovil', 'Stars Lane, Lysander Road', 'BA20 2GS'),
('York', 'Osbaldwick Link Road', 'YO10 3JB')
ON CONFLICT (name) DO UPDATE SET 
  address = EXCLUDED.address,
  postcode = EXCLUDED.postcode
WHERE test_centres.address IS NULL OR test_centres.address = '';